### ISSUE TITLE
T no se usa

### ISSUE THREAD

**Issue by RedPointyJackson** [thehellion/caos#1]
No será que D=2ηT en lugar de  D=2η? Si hago eso me sale un seno con overdamping o algo así.
![T=0](http://i.imgur.com/kYc9B90.png)

**Comment by thehellion** [comment]
It's not a bug, it's a feature. I'll add a temperatured version only for you, but next time double check before opening an inssue.

Thanks for your feedback.

**Comment by RedPointyJackson** [comment]
- [x]  Rekt
- [ ] Not Rekt
